[tool.black]
line-length = 120
py36 = false
extend-exclude = '''
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.pytest_cache
  | \.local
  | \venv
'''

[tool.isort]
skip_glob = [ "venv/*"]

# 以下配置为保持与 black 兼容
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.1.0"
tag_format = "v$version"
bump_message = "bump: version $current_version → $new_version [skip ci]"
