name: Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8~=4.0.1 flake8-colors~=0.1.9 black~=22.1.0 isort~=5.10.1
      - name: Analysing the code with flake8
        run: flake8 .
      - name: Analysing the code with black
        run: isort --check-only --df .
      - name: Analysing the code with isort
        run: black --check --diff .

  commitizen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-commitizen
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen
      - name: commitizen check
        run: cz check --rev-range origin/main..HEAD
