name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    environment: production
    name: Release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: main
          changelog_increment_filename: body.md
      - name: Release version
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: v${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PROT }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/.git/,/config/,/venv/,/.github/,.flake8,.gitignore,pyproject.toml,poetry.lock,body.md"
      - name: restart e-schedule
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ${{ secrets.TARGET }}
            ${{ secrets.TARGET }}/venv/bin/pip install -r requirements.txt
            supervisorctl restart e-schedule
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PROT }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}